name: 🧪 CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  frontend-test:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🟢 Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 📦 Install Frontend Dependencies
        run: |
          cd frontend
          npm install

      - name: 🧪 Run Frontend Tests
        run: |
          cd frontend
          npm run test

  backend-test:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🟢 Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 📦 Install Backend Dependencies
        run: |
          cd backend
          npm install

      # NUEVO PASO: Generar el cliente de Prisma
      - name: 🛠️ Generate Prisma Client
        env:
          DATABASE_URL: 'postgresql://fake:fake@localhost:5432/fake' # Prisma requiere esta variable para generar el cliente, aunque no se conecte
        run: |
          cd backend
          npx prisma generate

      - name: 🧪 Run Backend Tests
        env:
          DATABASE_URL: 'postgresql://fake:fake@localhost:5432/fake'
        run: |
          cd backend
          npm run test
